# Site settings
title: Jacob Mischka
email: jacob@mischka.me
# description: The personal website of Jacob Mischka.
baseurl: ""
url: "http://www.mischka.me"

twitter_username: jacobmischka
github_username:  jacobmischka
steam_username: jacobmischka

# Build settings
markdown: kramdown
permalink: pretty
exclude:
    - node_modules

sass:
    style: compressed

prose:
    siteurl: "http://www.mischka.me"
    media: "/images"
